
//ASSURES COMPLETE READING
//TAKES A FILE DESCRIPTOR, A STRING TO STORE WHAT YOU READ, AND MAX LENGTH TO READ
//RETURNS THE STRING WITH THE READ MATERIAL
char * readhelp(int , char *, int);

//ASSURES COMPLETE WRITING
//TAKES A FILE DESCRIPTOR, A STRING TO WRITE, THE NUMBER OF BYTES TO WRITE
writehelp(int SD, char * string, int len);
